volumes:
  ntripcaster-logs:

services:
  ntripcaster:
    build: .
    restart: unless-stopped
    ports:
      - 2101:2101
    volumes:
      - ./ntripcaster/conf:/usr/local/ntripcaster/conf
      - ntripcaster-logs:/usr/local/ntripcaster/logs
